version: '3.1'
services:
  database:
    image: postgres:14.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${JDBC_USER:-addvert}
      - POSTGRES_PASSWORD=${JDBC_PASSWORD:-typ3f0rm!}
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./sql/init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql
    command: postgres -c 'max_connections=200'

volumes:
  postgres:
    driver: local